### ISSUE TITLE
SVGo example refactor

### ISSUE THREAD

**Issue by ajstarks** [gophercises/image#1]
This gist: https://gist.github.com/ajstarks/8b1c24545264c20625073faa5e079a59
shows how you can adjust the bar width and separation.
Also, added variables to allow you to adjust aspects of the plot, and improve readability.

**Comment by joncalhoun** [comment]
This is *really* delayed, but I added it to the README and appreciate the gist :)

**Comment by ajstarks** [comment]
Thanks!
